[package]
name = "window_switcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inputbot = "0.5.1"
lazy_static = "1.4.0"
rdev = "0.5.2"
